GROUP_REPOS = [
    [
        "group a",
        "Gruppe_A",
        ["https://github.com/nissemand243/Gruppe_A"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group b",
        "Group Bee",
        ["https://github.com/DEV-OPS-Group-b/minitwit"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group c",
        "DevOpps",
        ["https://github.com/antonPalmFolkmann/DevOps2022"],
        "<minitwit_url>",
        "<mintwit_api_url>",
    ],
    [
        "group d",
        "DevelOps",
        ["https://github.com/DevelOpsITU/minitwit"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group e",
        "ASPirin",
        ["https://github.com/ChadIImus/Devoops/"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group f",
        "PayRespect",
        ["https://github.com/Chillhound/DevOps2022F"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group g",
        "Call Of Duty BlackOps",
        ["https://github.com/Faurby/BlackOps"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group h",
        "Continuous disintegration",
        ["https://github.com/Herover/itu-devops-h"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group i",
        "A-team",
        ["https://github.com/Arklaide/devopsITUproject"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group j",
        "Root",
        ["https://github.com/AlexBMJ/minitwit"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group k",
        "DevUps",
        ["https://github.com/HolgerGottChristensen/itu-devops"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group l",
        "iBois",
        ["https://github.com/aske-w/itu-minitwit"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group m",
        "DeadlyDevOps",
        ["https://github.com/DeadlyDevops/minitwit"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group n",
        "DevØps",
        ["https://github.com/emilravn/devops/"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group o",
        "TBD",
        ["https://github.com/Akongstad/DevOps-group-p"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group d",
        "DevelOps",
        ["https://github.com/DevelOpsITU/minitwit"],
        "<minitwit_url>",
        "<minitwit_api_url>",
    ],
    [
        "group r",
        "Rhododevdron",
        ["https://github.com/Devops-2022-Group-R/itu-minitwit"],
        "rhododevdron.swuwu.dk",
        "api.rhododevdron.swuwu.dk",
    ],
]
