GROUP_REPOS = [
    [
        "group a",
        "Nintendo Lawyers",
        ["https://github.com/ITU-DevOps2025-GROUP-A/itu-minitwit.git"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group b",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group c",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group d",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group e",
        "Docker Daze",
        ["https://github.com/Docker-Daze/itu-minitwit.git"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group f",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group g",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group h",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group i",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group j",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group k",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group l",
        "the happy group",
        ["https://github.com/DumbDane/DevOps-2025"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group m",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group n",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group o",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group p",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group q",
        "<name>",
        ["https://github.com/<organization|user>/<repository_name>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
]
