GROUP_REPOS = [
    [
        "group a",
        "<Name>",
        ["https://github.com/<TBA>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group b",
        "b",
        ["https://github.com/JesperFalkenberg/devops2021"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group c",
        "<Name>",
        ["https://github.com/<TBA>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group d",
        "<Name>",
        ["https://github.com/<TBA>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group e",
        "<Name>",
        ["https://github.com/<TBA>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group f",
        "Group Fibonacci",
        ["https://github.com/lauralunddahl/DevOps-GroupF"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group g",
        "Group G",
        ["https://github.com/JonasWG/ITU-DevOps/tree/main/itu-minitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group h",
        "<Name>",
        ["https://github.com/<TBA>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group i",
        "Mike",
        ["https://github.com/SanderBuK/DevOpsMinitwit"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group j",
        "Python Kindergarten",
        ["https://github.com/jokk-itu/PythonKindergarten"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group k",
        "<Name>",
        ["https://github.com/<TBA>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
    [
        "group l",
        "<Name>",
        ["https://github.com/<TBA>"],
        "http(s)://<TBA>/<FrontEndURL>",
        "http(s)://<TBA>/<APIURL>",
    ],
]
